Merge pull request #22 from VanSubstance/feature/basic-structure
VanSubstance/faker pull request #23
Opened 2023-10-16 01:43 UTC by gggangmin

2023-10-16 13:42 UTC, VanSubstance reviewed
@gggangmin 리뷰 종료

2023-10-16 13:42 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +}
아마 동일한 폴더 내의 다른 파일들을 보면 `namespace` 선언이 되어있는 것을 볼 수 있을겁니다
```
namespace ~~ {
  public class ~~~
}
```
식으로 선언해주는게 나을 듯합니다.
namespace는 java로 치면 `package`입니다.

2023-10-16 13:42 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +    public GameObject buttonTemplate;
**inspector** 상으로 오브젝트를 전달받기 위해 _public_ 접근자로 선언한 것이라면 
- _private_ 으로 선언
- [UnityEngine.SerializedField] attribute를 통해 **inspector** 에서 접근할 수 있게 처리
하는 것을 추천합니다.

또한 GameObject는 상대적으로 Transform보다 메모리 공간을 많이 차지합니다. 거의 동일하게 기능할 수 있는 Tansform을 사용하는 것을 추천합니다.

2023-10-16 13:42 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +        for(int i =0; i < btnCount; i++){
띄어쓰기 마저 해주시기 바랍니다.
```
 for ( int i = 0; i < btnCount; i++) {
```

2023-10-16 13:42 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +            GameObject btn = (GameObject)Instantiate(buttonTemplate,scrollViewContent.transform);
메모리 최적화를 위해,  지역 변수 선언은 지양하는 것이 좋습니다.
- 추가적으로 사용할 가능성이 있다 -> 클래스 필드에 선언
을 해주시기 바랍니다.
만약 추가 사용 가능성이 없다면 리턴값을 보관하지 않도록 합시다.

2023-10-16 13:42 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +    }
사용하지 않는 내장 합수는 메모리 최적화를 위해 삭제해주시기 바랍니다.

2023-10-16 13:42 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +using System.Collections.Generic;
현재 해당 파일 내에서 Generic namespace를 호출하는 부분이 없는 것으로 보입니다.
만약 사용되지 않는다면 삭제해주시기 바랍니다.

2023-10-16 13:47 UTC, VanSubstance commented
서둘러서 할 필요 없음
본인이 하고싶은만큼만 하면 된다 무리 안하고

2023-10-20 15:11 UTC, VanSubstance requested changes
@gggangmin 리뷰 완료

2023-10-20 15:11 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +//using System.Collections.Generic;
사용치 않는 코드는 삭제해주시기 바랍니다.
나중에 타인의 코드와 merge 하는 과정에 있어 불필요한 충돌이 일어날 가능성이 있습니다.

2023-10-20 15:11 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +    // Start is called before the first frame update
불필요한 주석 (ex: 자동 생성되는 주석 등)은 삭제해주시기 바랍니다.

2023-10-20 15:11 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +}
개행은 스페이스바 2칸을 원칙으로 합니다.

```
namespace A
{
  public class B
  {
    ...
  }
}
```

2023-10-20 15:11 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +            //Transform btn = (Transform)Instantiate(buttonTemplate,scrollViewContent.transform);
사용하지 않는 코드는 삭제해주시기 바랍니다.
나중에 타인의 코드와 merge 하는 과정에 있어 불필요한 충돌이 일어날 가능성이 있습니다.

2023-10-20 15:11 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +    public int btnCount = 10;
임시로 사용하는 변수인거죠 ?

2023-10-31 03:54 UTC, gggangmin commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +    public int btnCount = 10;
네, 맞습니다.

2023-10-31 03:58 UTC, merged