Feature/system UI
VanSubstance/faker pull request #24
Opened 2023-10-24 13:52 UTC by wnsals1346

1. 몇몇의 강의를 빠르게 훑어 봤는데, 강의마다 제작 방식이 좀 다르던데
버전에 따라서 그런 것인지? 너가 만드는 방식을 대충 이해해보니까.
Object를 만들고 각각의 Object에 맞는 Script를 제작하여서 Component로 넣어주면
Unity가 Inspector탭에서 알아서 variables들의 Input을 보여주고 거기에 적는 형식으로 제작하는 게 맞나?

자꾸 띄엄뛰엄하다가 계속 방향을 잘 못잡겠어서 다른거 대충 따라하면서 이것저것 구경만 하다가 시간을 많이 써버렸다.
이제 회사업무도 올해말까지 프리해서 야근도 없을 예정이고 좀더 시간내서 집중해볼게

지금 내린결론은 

앞으로 제작하는 큰 방향을 생각할 때, 내가 빨리 터득해야 할 부분이
1) Object Pulling 같은 유니티에서 Object를 다루는 방식과 같은 게임제작(Unity) 로직의 이해.
2) Unity에서 여러가지 Object를 만드는 방식 (UI, Unit, 상호작용 등)
3) Controller같은 Script 작성법 (C#언어문법)

요렇게 3가지로 생각하고 Object를 만들고 Script를 작성하고 Component로 추가하고 Prefab으로 관리
그외 게임제작기술 등을 익혀서 적용

이런 식으로 공부해나간다고 생각하면 될까?

2. Pagination Manager Component의 위치는 정해진 규칙이 있는거야?

3. 보통 여러 형식의 Prefab을 가진 버튼이 있을텐데 그 버튼에 대한 Script를 구분해서 작성하는지? 아니면 한Script에 
분기 처리든 variable을 이용하든 통용되는 Script를 작성하는 지??

2023-10-25 05:47 UTC, VanSubstance commented
우선 질문에 대한 답변부터 진행하겠습니다.

---
Q1. 터득해야 할 것
- 순서 자체가 크게 어긋나지는 않았으나, **1 -> 3 순서 + 상시 2번** 이 좀 더 정확할 것으로 보입니다.
- Controller 란 일반적으로 MonoBehaviour를 상속하여 **게임 오브젝트를 컨트롤 하는 클래스 오브젝트** 를 지칭하며, 그렇기 때문에 사실상 Script 작성법은 따로 공부하는 것이 아니라 1, 3번을 터득하는 과정에서 실시간으로 터득해야 할 것으로 보입니다.
---
Q2. Component의 위치 (어떤 게임 오브젝트에 할당되어야 하는가 ?)
- 최초에 사용된 해당 시스템의 계층 구조를 그대로 따라갑니다.
- 실제 Scene에서 해당 시스템이 사용된 예시가 있는 것으로 알고 있습니다. 해당 계층 구조를 그대로 따라가면 될 것으로 보입니다.
---
Q3. Prefab의 종류와 분기 처리
- 일반적으로는 상속을 통해 구현합니다.
- Controller의 분기를 나누는 기준은 일반적으로 **해당 게임 오브젝트의 구성** 입니다.
  - **구성 게임 오브젝트가 동일할 때**는 같은 Controller를 사용하는 것이 맞습니다.
  - 다를때는 공통된 게임 오브젝트를 부모로 하고 상속을 통해 구현합니다.

2023-10-25 05:49 UTC, VanSubstance requested changes
최초에 말씀드렸던 부분입니다.
Scene에서의 충돌을 배제하기 위해, `SampleScene_본인이름` 으로 Scene 공간을 분리하여 작업해주시기 바랍니다.
`SampleScene_양승혁.unity` 파일은 수정사항이 없어야 합니다.

2023-11-07 10:37 UTC, wnsals1346 commented
1. Object 명칭 정하는게 어려워서 잘못됐든 뭐하든 신경쓰지 않았습니다.
2. 실제로 능력치는 업그레이드할 때는 특정 규칙이나 계산에 의해 능력치가 추가될 것이지만 일단은 1씩 증가하는걸로 고정했습니다.
3. 현재까지 작업 내역
기존에 만들어두었던 Header에 업그레이드 버튼을 누르면 유닛 유형 레이어가 나오고 특정 유형을 선택하면 상세 능력치를 업그레이드할 수 있는 레이어가 나옵니다. 특정 행의 버튼을 누르면 그 능력치가 1 증가합니다.

2023-11-08 06:06 UTC, VanSubstance requested changes
@wnsals1346 리뷰 완료.
현재 실행은 해보지 않고, 코드적인 부분 리뷰만 진행하였습니다.

리뷰 사항 확인 부탁드립니다.

2023-11-08 06:06 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/Button/UpgradeButtonController.cs
개행 space 4칸 -> 2칸

2023-11-08 06:06 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/Button/UpgradeButtonController.cs
> +	    [SerializeField]
줄맞춤

2023-11-08 06:06 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/Button/UpgradeButtonController.cs
> +		private TextMeshProUGUI statValue;
특별한 의미가 없다면 나열 선언 부탁드립니다.
```
		[SerializeField]
		private TextMeshProUGUI statName,statValue;
```

2023-11-08 06:06 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/Button/UpgradeButtonController.cs
전체적으로 코드 snippet 적용 부탁드립니다.

2023-11-08 06:06 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/Button/UpgradeButtonController.cs
> +		statValue.text = "현재 : " + level;
`String` 타입끼리의 연산은 상대적으로 비용이 비쌉니다.
String.join 또는 $"" 활용으로 부탁드립니다.
```
		statValue.text = $"현재 : {level}";
```

2023-11-10 06:40 UTC, wnsals1346 commented on ProjectFaker/Assets/Scripts/UI/Button/UpgradeButtonController.cs
어떤 부분을 말하는건지 이해를 못했습니다.

2023-11-20 12:12 UTC, VanSubstance approved these changes

2023-11-20 12:12 UTC, merged