Feature/scroll view2
VanSubstance/faker pull request #26
Opened 2023-11-02 10:26 UTC by gggangmin

Shop PCT의 기존 ScrollViewContent를 ScrollViewContent_class로 변경하고 ScrollViewContent_item을 추가함
ScrollViewContent_class의 버튼 눌렀을 때 해당 버튼의 id를 ScrollViewContent_item로 전송하며 화면 출력
기존의 ScrollViewContent_class는 비활성화

2023-11-04 08:30 UTC, VanSubstance commented
Merge 대상 branch를 dev로 바꿔주세요;

2023-11-06 13:55 UTC, VanSubstance commented
정확히 무엇을 의도한 기능인지 설명이 필요합니다.
어떤 목적으로 해당 기능을 만드신건지 여쭤봐도 될까요 ?

2023-11-06 14:25 UTC, VanSubstance commented
https://github.com/VanSubstance/faker/pull/23
이전 PR의 리뷰가 제대로 반영되지 않았습니다.
이전 리뷰 반영 후 이번 코드 리뷰 진행하겠습니다. 수정 부탁드립니다.

2023-11-06 14:33 UTC, VanSubstance requested changes
이전 PR에서 남겼던 리뷰가 제대로 반영되지 않은 것이 보입니다.
이전 리뷰와 이번 리뷰 전부 반영 부탁드립니다.

2023-11-06 14:33 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +    private Transform scrollViewContent_item;
private 변수 명은 camelCase를 사용하는 것을 원칙으로 합니다 .
`scrollViewContentClass`
`scrollViewContentItem`

2023-11-06 14:33 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +    public int itemBtnCount=5;
public 변수 명은 CapitalCase를 사용하는 것을 원칙으로 합니다.
`ClassBtnCount = 4;`
`ItemBtnCount = 5;`

2023-11-06 14:33 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
>      void Start()
접근자는 반드시 명시합니다.
`private`, `protected`, `public`

2023-11-06 14:33 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +    void ActiveScrollViewContent_class()
**접근자 명시**

2023-11-06 14:33 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +    void ActiveScrollViewContent_item(int classId)
**접근자 명시**

2023-11-06 14:33 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +    void ActiveScrollViewContent_class()
Unity의 함수명은 `CapitalCase`를 원칙으로 합니다.

2023-11-06 14:33 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +    void ActiveScrollViewContent_item(int classId)
Unity의 함수명은 `CapitalCase`를 원칙으로 합니다.

2023-11-06 14:33 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
>      private Transform buttonTemplate;
현재 코드에서 `buttonTemplate` 오브젝트의 UnityEngine.UI.Button 컴포넌트만 불러와서 사용하는 것으로 보입니다.
그렇다면 `Transform` 보다 해당 타입인 `UnityEngine.UI.Button`으로 선언해서 사용하는 것이 좋습니다.

2023-11-06 14:33 UTC, VanSubstance commented on ProjectFaker/Assets/Scripts/UI/ButtonManager.cs
> +        Transform button = Instantiate(buttonTemplate,scrollViewContent_class.transform);
`scrollViewContent_class`가 이미 `Transform`인 것으로 보입니다.
`~~.transform`을 호출할 필요가 없습니다.

2023-11-08 08:00 UTC, gggangmin commented
> 이전 PR에서 남겼던 리뷰가 제대로 반영되지 않은 것이 보입니다. 이전 리뷰와 이번 리뷰 전부 반영 부탁드립니다.

확인되면 클로즈하겠습니다.

2023-11-14 14:32 UTC, VanSubstance approved these changes
lgtm :ant:

2023-11-14 14:32 UTC, merged